package com.projeto.erp.enumeracoes;

public enum MotivoAlteracaoSalario {
    ADMISSAO, REAJUSTE_SALARIO_MINIMO, DISSIDIO, ACORDO_COLETIVO, PISO_SALARIAL_ESTADUAL, PROMOCAO, MUDANCA_CARGO, SALARIO_SUBSTITUICAO, ADICIONAL_QUALIFICACAO
}
